name: Keep Alive
on:
  schedule:
    - cron: '*/10 * * * *' # Every 10 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping server
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %T")
          curl -X GET "https://starboom.onrender.com/api/keep-alive?ping=$TIMESTAMP"